services:
    bundleModel:
        class: Opine\Bundle\Model
        arguments:
            - %root%
    bundleBuild:
        class: Opine\Bundle\Build
        arguments:
            - %root%
            - @route
