imports:
    - package-container.yml
    - ../../vendor/opine/route/config/containes/package-container.yml
    - ../../vendor/opine/config/config/containers/package-container.yml
    - ../../vendor/opine/container/config/containers/package-container.yml